Repost of previous pull request
ruby-jp/websocket-client-simple pull request #4
Opened 2021-12-30 11:06 UTC by fuyuton

This pull request contains the following:
Are you doing well? (I'm sorry I'm not used to it)

Added to use SNI
close?の追加
add reference variable
Update websocket-client-simple.gemspec
fix SSLError

2021-12-30 20:12 UTC, unasuke requested changes
Thank you for your pull request! 😄  And I have a favor to ask of you.

You wrote that in the description. 

> Added to use SNI
> close?の追加
> add reference variable
> Update websocket-client-simple.gemspec
> fix SSLError


It looks like doing some things in one pull request.
I want you to create one pull request for one purpose.

2021-12-30 20:12 UTC, unasuke commented on lib/websocket-client-simple/version.rb
> +      VERSION = "0.3.3"
Don't edit the version, please. The version is changed at release by the maintainer.

2021-12-30 20:12 UTC, unasuke commented on websocket-client-simple.gemspec
> +  spec.add_dependency "event_emitter", "~> 0.2.6"
Why did you edit those lines? It does not affect actually and not breaking, also not needed.

2021-12-31 10:51 UTC, fuyuton commented
got it.

2021-12-31 10:51 UTC, closed without merging